/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "filament.exports.download": [
        {
            "name": "export",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.imports.failed-rows.download": [
        {
            "name": "import",
            "required": true,
            "binding": "id"
        }
    ],
    "filament.admin.auth.login": [],
    "filament.admin.auth.password-reset.request": [],
    "filament.admin.auth.password-reset.reset": [],
    "filament.admin.auth.logout": [],
    "filament.admin.auth.profile": [],
    "filament.admin.pages.dashboard": [],
    "filament.admin.resources.stores.index": [],
    "filament.admin.resources.stores.create": [],
    "filament.admin.resources.stores.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.admin.resources.users.index": [],
    "filament.admin.resources.users.create": [],
    "filament.admin.resources.users.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.app.auth.login": [],
    "filament.app.auth.password-reset.request": [],
    "filament.app.auth.password-reset.reset": [],
    "filament.app.auth.logout": [],
    "filament.app.auth.email-verification.prompt": [],
    "filament.app.auth.email-verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "filament.app.pages.dashboard": [],
    "filament.app.pages.create-payment": [],
    "filament.app.resources.bank-accounts.index": [],
    "filament.app.resources.bank-accounts.create": [],
    "filament.app.resources.bank-accounts.edit": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.app.resources.payments.index": [],
    "filament.app.resources.payments.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.app.resources.stores.index": [],
    "filament.app.resources.stores.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.app.resources.transactions.index": [],
    "filament.app.resources.transactions.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.app.resources.user-subscriptions.index": [],
    "filament.app.resources.user-subscriptions.create": [],
    "filament.app.resources.user-subscriptions.view": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.app.resources.user-subscriptions.payment": [
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.store.auth.login": [],
    "filament.store.auth.password-reset.request": [],
    "filament.store.auth.password-reset.reset": [],
    "filament.store.auth.register": [],
    "filament.store.auth.logout": [],
    "filament.store.auth.profile": [],
    "filament.store.auth.email-verification.prompt": [],
    "filament.store.auth.email-verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "filament.store.tenant.registration": [],
    "filament.store.pages.dashboard": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.tenant.profile": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.pages.billing": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.pages.customer-create": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.resources.bank-accounts.index": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.resources.bank-accounts.create": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.resources.bank-accounts.edit": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.store.resources.customers.index": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.resources.customers.edit": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.store.resources.employees.index": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.resources.employees.create": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.resources.employees.edit": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.store.resources.payments.index": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.resources.payments.view": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.store.resources.plans.index": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.resources.plans.create": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.resources.plans.edit": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.store.resources.subscriptions.index": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.resources.subscriptions.create": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.resources.subscriptions.edit": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.store.resources.transactions.index": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        }
    ],
    "filament.store.resources.transactions.view": [
        {
            "name": "tenant",
            "required": true,
            "binding": "slug"
        },
        {
            "name": "record",
            "required": true
        }
    ],
    "filament.store.tenant": [],
    "horizon.stats.index": [],
    "horizon.workload.index": [],
    "horizon.masters.index": [],
    "horizon.monitoring.index": [],
    "horizon.monitoring.store": [],
    "horizon.monitoring-tag.paginate": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.monitoring-tag.destroy": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.jobs-metrics.index": [],
    "horizon.jobs-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.queues-metrics.index": [],
    "horizon.queues-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.index": [],
    "horizon.jobs-batches.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.retry": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.pending-jobs.index": [],
    "horizon.completed-jobs.index": [],
    "horizon.silenced-jobs.index": [],
    "horizon.failed-jobs.index": [],
    "horizon.failed-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.retry-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.index": [
        {
            "name": "view",
            "required": false
        }
    ],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "passwordless.login": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "magiclink.send": [],
    "magiclink.login": []
}
}
export {};
